baseURL = 'https://www.hydroponicswall.com/'
languageCode = 'en-us'
title = 'Hydroponics Wall'
theme = 'ananke'
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1

[params]
    custom_css = ["custom.scss"]
